//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxAndroid/rxandroid/build/generated/source/apt/test/AllTests.java
//

#include "AllTests.h"
#include "CoTouchlabDopplTestingDopplJunitTestHelper.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "RxAndroidPluginsRxAndroidPluginsTest.h"
#include "RxAndroidSchedulersAndroidSchedulersTest.h"
#include "RxAndroidSchedulersHandlerSchedulerTest.h"
#include "org/junit/runner/notification/RunListener.h"

@implementation AllTests

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  AllTests_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (jint)runAllTests {
  return AllTests_runAllTests();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(runAllTests);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _AllTests = { "AllTests", NULL, NULL, methods, NULL, 7, 0x11, 2, 0, -1, -1, -1, -1, -1 };
  return &_AllTests;
}

@end

void AllTests_init(AllTests *self) {
  NSObject_init(self);
}

AllTests *new_AllTests_init() {
  J2OBJC_NEW_IMPL(AllTests, init)
}

AllTests *create_AllTests_init() {
  J2OBJC_CREATE_IMPL(AllTests, init)
}

jint AllTests_runAllTests() {
  AllTests_initialize();
  return CoTouchlabDopplTestingDopplJunitTestHelper_runWithIOSClassArray_withOrgJunitRunnerNotificationRunListener_([IOSObjectArray arrayWithObjects:(id[]){ RxAndroidPluginsRxAndroidPluginsTest_class_(), RxAndroidSchedulersAndroidSchedulersTest_class_(), RxAndroidSchedulersHandlerSchedulerTest_class_() } count:3 type:IOSClass_class_()], create_OrgJunitRunnerNotificationRunListener_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(AllTests)
