//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxAndroid/rxandroid/src/test/java/BackgroundTests.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BackgroundTests")
#ifdef RESTRICT_BackgroundTests
#define INCLUDE_ALL_BackgroundTests 0
#else
#define INCLUDE_ALL_BackgroundTests 1
#endif
#undef RESTRICT_BackgroundTests

#if !defined (BackgroundTests_) && (INCLUDE_ALL_BackgroundTests || defined(INCLUDE_BackgroundTests))
#define BackgroundTests_

@interface BackgroundTests : NSObject

#pragma mark Public

- (instancetype)init;

+ (jint)runAllTests;

+ (void)runAllTestsBackground;

@end

J2OBJC_EMPTY_STATIC_INIT(BackgroundTests)

FOUNDATION_EXPORT void BackgroundTests_init(BackgroundTests *self);

FOUNDATION_EXPORT BackgroundTests *new_BackgroundTests_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT BackgroundTests *create_BackgroundTests_init();

FOUNDATION_EXPORT void BackgroundTests_runAllTestsBackground();

FOUNDATION_EXPORT jint BackgroundTests_runAllTests();

J2OBJC_TYPE_LITERAL_HEADER(BackgroundTests)

#endif

#pragma pop_macro("INCLUDE_ALL_BackgroundTests")
