//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxAndroid/rxandroid/src/test/java/rx/android/schedulers/HandlerSchedulerTest.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "RxAndroidSchedulersHandlerScheduler.h"
#include "RxAndroidSchedulersHandlerSchedulerTest.h"
#include "java/lang/NullPointerException.h"
#include "java/lang/annotation/Annotation.h"
#include "org/junit/Assert.h"
#include "org/junit/Test.h"

__attribute__((unused)) static IOSObjectArray *RxAndroidSchedulersHandlerSchedulerTest__Annotations$0();

@implementation RxAndroidSchedulersHandlerSchedulerTest

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RxAndroidSchedulersHandlerSchedulerTest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)fromNullThrows {
  @try {
    RxAndroidSchedulersHandlerScheduler_fromWithAndroidOsHandler_(nil);
    OrgJunitAssert_fail();
  }
  @catch (JavaLangNullPointerException *e) {
    OrgJunitAssert_assertEqualsWithId_withId_(@"handler == null", [((JavaLangNullPointerException *) nil_chk(e)) getMessage]);
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 0, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(fromNullThrows);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { (void *)&RxAndroidSchedulersHandlerSchedulerTest__Annotations$0 };
  static const J2ObjcClassInfo _RxAndroidSchedulersHandlerSchedulerTest = { "HandlerSchedulerTest", "rx.android.schedulers", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_RxAndroidSchedulersHandlerSchedulerTest;
}

@end

void RxAndroidSchedulersHandlerSchedulerTest_init(RxAndroidSchedulersHandlerSchedulerTest *self) {
  NSObject_init(self);
}

RxAndroidSchedulersHandlerSchedulerTest *new_RxAndroidSchedulersHandlerSchedulerTest_init() {
  J2OBJC_NEW_IMPL(RxAndroidSchedulersHandlerSchedulerTest, init)
}

RxAndroidSchedulersHandlerSchedulerTest *create_RxAndroidSchedulersHandlerSchedulerTest_init() {
  J2OBJC_CREATE_IMPL(RxAndroidSchedulersHandlerSchedulerTest, init)
}

IOSObjectArray *RxAndroidSchedulersHandlerSchedulerTest__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RxAndroidSchedulersHandlerSchedulerTest)
