//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxAndroid/rxandroid/src/test/java/rx/android/MainThreadSubscriptionTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxAndroidMainThreadSubscriptionTest")
#ifdef RESTRICT_RxAndroidMainThreadSubscriptionTest
#define INCLUDE_ALL_RxAndroidMainThreadSubscriptionTest 0
#else
#define INCLUDE_ALL_RxAndroidMainThreadSubscriptionTest 1
#endif
#undef RESTRICT_RxAndroidMainThreadSubscriptionTest

#if !defined (RxAndroidMainThreadSubscriptionTest_) && (INCLUDE_ALL_RxAndroidMainThreadSubscriptionTest || defined(INCLUDE_RxAndroidMainThreadSubscriptionTest))
#define RxAndroidMainThreadSubscriptionTest_

@interface RxAndroidMainThreadSubscriptionTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)onUnsubscribePostsOffMainThread;

- (void)onUnsubscribeRunsSyncOnMainThread;

- (void)unsubscribeTwiceDoesNotRunTwice;

- (void)verifyDoesNotThrowOnMainThread;

- (void)verifyThrowsOffMainThread;

@end

J2OBJC_EMPTY_STATIC_INIT(RxAndroidMainThreadSubscriptionTest)

FOUNDATION_EXPORT void RxAndroidMainThreadSubscriptionTest_init(RxAndroidMainThreadSubscriptionTest *self);

FOUNDATION_EXPORT RxAndroidMainThreadSubscriptionTest *new_RxAndroidMainThreadSubscriptionTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxAndroidMainThreadSubscriptionTest *create_RxAndroidMainThreadSubscriptionTest_init();

J2OBJC_TYPE_LITERAL_HEADER(RxAndroidMainThreadSubscriptionTest)

#endif

#pragma pop_macro("INCLUDE_ALL_RxAndroidMainThreadSubscriptionTest")
