//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxAndroid/rxandroid/src/test/java/rx/android/schedulers/AndroidSchedulersTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxAndroidSchedulersAndroidSchedulersTest")
#ifdef RESTRICT_RxAndroidSchedulersAndroidSchedulersTest
#define INCLUDE_ALL_RxAndroidSchedulersAndroidSchedulersTest 0
#else
#define INCLUDE_ALL_RxAndroidSchedulersAndroidSchedulersTest 1
#endif
#undef RESTRICT_RxAndroidSchedulersAndroidSchedulersTest

#if !defined (RxAndroidSchedulersAndroidSchedulersTest_) && (INCLUDE_ALL_RxAndroidSchedulersAndroidSchedulersTest || defined(INCLUDE_RxAndroidSchedulersAndroidSchedulersTest))
#define RxAndroidSchedulersAndroidSchedulersTest_

@interface RxAndroidSchedulersAndroidSchedulersTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)mainThreadCallsThroughToHook;

- (void)setUpAndTearDown;

@end

J2OBJC_EMPTY_STATIC_INIT(RxAndroidSchedulersAndroidSchedulersTest)

FOUNDATION_EXPORT void RxAndroidSchedulersAndroidSchedulersTest_init(RxAndroidSchedulersAndroidSchedulersTest *self);

FOUNDATION_EXPORT RxAndroidSchedulersAndroidSchedulersTest *new_RxAndroidSchedulersAndroidSchedulersTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxAndroidSchedulersAndroidSchedulersTest *create_RxAndroidSchedulersAndroidSchedulersTest_init();

J2OBJC_TYPE_LITERAL_HEADER(RxAndroidSchedulersAndroidSchedulersTest)

#endif

#pragma pop_macro("INCLUDE_ALL_RxAndroidSchedulersAndroidSchedulersTest")
