//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxAndroid/rxandroid/src/test/java/rx/android/schedulers/LooperSchedulerTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxAndroidSchedulersLooperSchedulerTest")
#ifdef RESTRICT_RxAndroidSchedulersLooperSchedulerTest
#define INCLUDE_ALL_RxAndroidSchedulersLooperSchedulerTest 0
#else
#define INCLUDE_ALL_RxAndroidSchedulersLooperSchedulerTest 1
#endif
#undef RESTRICT_RxAndroidSchedulersLooperSchedulerTest

#if !defined (RxAndroidSchedulersLooperSchedulerTest_) && (INCLUDE_ALL_RxAndroidSchedulersLooperSchedulerTest || defined(INCLUDE_RxAndroidSchedulersLooperSchedulerTest))
#define RxAndroidSchedulersLooperSchedulerTest_

@interface RxAndroidSchedulersLooperSchedulerTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)actionMissingErrorHandlerRoutedToHookAndThreadHandler;

- (void)fromNullThrows;

- (void)schedulePostsActionImmediately;

- (void)schedulerHookIsUsed;

- (void)scheduleWithDelayPostsActionWithDelay;

- (void)setUp;

- (void)tearDown;

- (void)throwingActionRoutedToHookAndThreadHandler;

- (void)unsubscribeCancelsScheduledAction;

- (void)unsubscribeCancelsScheduledActionWithDelay;

- (void)unsubscribeState;

- (void)workerUnsubscribeState;

- (void)workerUnsubscriptionCancelsScheduled;

- (void)workerUnsubscriptionDuringSchedulingCancelsScheduledAction;

- (void)workerUnsubscriptionPreventsScheduling;

@end

J2OBJC_EMPTY_STATIC_INIT(RxAndroidSchedulersLooperSchedulerTest)

FOUNDATION_EXPORT void RxAndroidSchedulersLooperSchedulerTest_init(RxAndroidSchedulersLooperSchedulerTest *self);

FOUNDATION_EXPORT RxAndroidSchedulersLooperSchedulerTest *new_RxAndroidSchedulersLooperSchedulerTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxAndroidSchedulersLooperSchedulerTest *create_RxAndroidSchedulersLooperSchedulerTest_init();

J2OBJC_TYPE_LITERAL_HEADER(RxAndroidSchedulersLooperSchedulerTest)

#endif

#pragma pop_macro("INCLUDE_ALL_RxAndroidSchedulersLooperSchedulerTest")
