//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxAndroid/rxandroid/src/test/java/rx/android/testutil/EmptyScheduler.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxAndroidTestutilEmptyScheduler")
#ifdef RESTRICT_RxAndroidTestutilEmptyScheduler
#define INCLUDE_ALL_RxAndroidTestutilEmptyScheduler 0
#else
#define INCLUDE_ALL_RxAndroidTestutilEmptyScheduler 1
#endif
#undef RESTRICT_RxAndroidTestutilEmptyScheduler

#if !defined (RxAndroidTestutilEmptyScheduler_) && (INCLUDE_ALL_RxAndroidTestutilEmptyScheduler || defined(INCLUDE_RxAndroidTestutilEmptyScheduler))
#define RxAndroidTestutilEmptyScheduler_

#define RESTRICT_RxScheduler 1
#define INCLUDE_RxScheduler 1
#include "RxScheduler.h"

@class RxScheduler_Worker;

@interface RxAndroidTestutilEmptyScheduler : RxScheduler

#pragma mark Public

- (instancetype)init;

- (RxScheduler_Worker *)createWorker;

@end

J2OBJC_EMPTY_STATIC_INIT(RxAndroidTestutilEmptyScheduler)

FOUNDATION_EXPORT void RxAndroidTestutilEmptyScheduler_init(RxAndroidTestutilEmptyScheduler *self);

FOUNDATION_EXPORT RxAndroidTestutilEmptyScheduler *new_RxAndroidTestutilEmptyScheduler_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxAndroidTestutilEmptyScheduler *create_RxAndroidTestutilEmptyScheduler_init();

J2OBJC_TYPE_LITERAL_HEADER(RxAndroidTestutilEmptyScheduler)

#endif

#pragma pop_macro("INCLUDE_ALL_RxAndroidTestutilEmptyScheduler")
