//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxAndroid/rxandroid/src/test/java/rx/android/schedulers/ResetSchedulersTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxAndroidSchedulersResetSchedulersTest")
#ifdef RESTRICT_RxAndroidSchedulersResetSchedulersTest
#define INCLUDE_ALL_RxAndroidSchedulersResetSchedulersTest 0
#else
#define INCLUDE_ALL_RxAndroidSchedulersResetSchedulersTest 1
#endif
#undef RESTRICT_RxAndroidSchedulersResetSchedulersTest

#if !defined (RxAndroidSchedulersResetSchedulersTest_) && (INCLUDE_ALL_RxAndroidSchedulersResetSchedulersTest || defined(INCLUDE_RxAndroidSchedulersResetSchedulersTest))
#define RxAndroidSchedulersResetSchedulersTest_

@interface RxAndroidSchedulersResetSchedulersTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)reset;

@end

J2OBJC_EMPTY_STATIC_INIT(RxAndroidSchedulersResetSchedulersTest)

FOUNDATION_EXPORT void RxAndroidSchedulersResetSchedulersTest_init(RxAndroidSchedulersResetSchedulersTest *self);

FOUNDATION_EXPORT RxAndroidSchedulersResetSchedulersTest *new_RxAndroidSchedulersResetSchedulersTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxAndroidSchedulersResetSchedulersTest *create_RxAndroidSchedulersResetSchedulersTest_init();

J2OBJC_TYPE_LITERAL_HEADER(RxAndroidSchedulersResetSchedulersTest)

#endif

#pragma pop_macro("INCLUDE_ALL_RxAndroidSchedulersResetSchedulersTest")
