//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxAndroid/rxandroid/src/test/java/rx/android/plugins/RxAndroidPluginsTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxAndroidPluginsRxAndroidPluginsTest")
#ifdef RESTRICT_RxAndroidPluginsRxAndroidPluginsTest
#define INCLUDE_ALL_RxAndroidPluginsRxAndroidPluginsTest 0
#else
#define INCLUDE_ALL_RxAndroidPluginsRxAndroidPluginsTest 1
#endif
#undef RESTRICT_RxAndroidPluginsRxAndroidPluginsTest

#if !defined (RxAndroidPluginsRxAndroidPluginsTest_) && (INCLUDE_ALL_RxAndroidPluginsRxAndroidPluginsTest || defined(INCLUDE_RxAndroidPluginsRxAndroidPluginsTest))
#define RxAndroidPluginsRxAndroidPluginsTest_

@interface RxAndroidPluginsRxAndroidPluginsTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)registeredSchedulersHookIsUsed;

- (void)registerSchedulersHookTwiceFails;

@end

J2OBJC_EMPTY_STATIC_INIT(RxAndroidPluginsRxAndroidPluginsTest)

FOUNDATION_EXPORT void RxAndroidPluginsRxAndroidPluginsTest_init(RxAndroidPluginsRxAndroidPluginsTest *self);

FOUNDATION_EXPORT RxAndroidPluginsRxAndroidPluginsTest *new_RxAndroidPluginsRxAndroidPluginsTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxAndroidPluginsRxAndroidPluginsTest *create_RxAndroidPluginsRxAndroidPluginsTest_init();

J2OBJC_TYPE_LITERAL_HEADER(RxAndroidPluginsRxAndroidPluginsTest)

#endif

#pragma pop_macro("INCLUDE_ALL_RxAndroidPluginsRxAndroidPluginsTest")
