//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxAndroid/rxandroid/src/test/java/rx/android/testutil/CountingAction.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxAndroidTestutilCountingAction")
#ifdef RESTRICT_RxAndroidTestutilCountingAction
#define INCLUDE_ALL_RxAndroidTestutilCountingAction 0
#else
#define INCLUDE_ALL_RxAndroidTestutilCountingAction 1
#endif
#undef RESTRICT_RxAndroidTestutilCountingAction

#if !defined (RxAndroidTestutilCountingAction_) && (INCLUDE_ALL_RxAndroidTestutilCountingAction || defined(INCLUDE_RxAndroidTestutilCountingAction))
#define RxAndroidTestutilCountingAction_

#define RESTRICT_JavaUtilConcurrentAtomicAtomicInteger 1
#define INCLUDE_JavaUtilConcurrentAtomicAtomicInteger 1
#include "java/util/concurrent/atomic/AtomicInteger.h"

#define RESTRICT_RxFunctionsAction0 1
#define INCLUDE_RxFunctionsAction0 1
#include "RxFunctionsAction0.h"

@interface RxAndroidTestutilCountingAction : JavaUtilConcurrentAtomicAtomicInteger < RxFunctionsAction0 > {
 @public
  jboolean uiThread_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithBoolean:(jboolean)uiThread;

- (void)call;

@end

J2OBJC_EMPTY_STATIC_INIT(RxAndroidTestutilCountingAction)

FOUNDATION_EXPORT void RxAndroidTestutilCountingAction_init(RxAndroidTestutilCountingAction *self);

FOUNDATION_EXPORT RxAndroidTestutilCountingAction *new_RxAndroidTestutilCountingAction_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxAndroidTestutilCountingAction *create_RxAndroidTestutilCountingAction_init();

FOUNDATION_EXPORT void RxAndroidTestutilCountingAction_initWithBoolean_(RxAndroidTestutilCountingAction *self, jboolean uiThread);

FOUNDATION_EXPORT RxAndroidTestutilCountingAction *new_RxAndroidTestutilCountingAction_initWithBoolean_(jboolean uiThread) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxAndroidTestutilCountingAction *create_RxAndroidTestutilCountingAction_initWithBoolean_(jboolean uiThread);

J2OBJC_TYPE_LITERAL_HEADER(RxAndroidTestutilCountingAction)

#endif

#pragma pop_macro("INCLUDE_ALL_RxAndroidTestutilCountingAction")
