//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/RxAndroid/rxandroid/src/test/java/rx/android/schedulers/HandlerSchedulerTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxAndroidSchedulersHandlerSchedulerTest")
#ifdef RESTRICT_RxAndroidSchedulersHandlerSchedulerTest
#define INCLUDE_ALL_RxAndroidSchedulersHandlerSchedulerTest 0
#else
#define INCLUDE_ALL_RxAndroidSchedulersHandlerSchedulerTest 1
#endif
#undef RESTRICT_RxAndroidSchedulersHandlerSchedulerTest

#if !defined (RxAndroidSchedulersHandlerSchedulerTest_) && (INCLUDE_ALL_RxAndroidSchedulersHandlerSchedulerTest || defined(INCLUDE_RxAndroidSchedulersHandlerSchedulerTest))
#define RxAndroidSchedulersHandlerSchedulerTest_

@interface RxAndroidSchedulersHandlerSchedulerTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)fromNullThrows;

@end

J2OBJC_EMPTY_STATIC_INIT(RxAndroidSchedulersHandlerSchedulerTest)

FOUNDATION_EXPORT void RxAndroidSchedulersHandlerSchedulerTest_init(RxAndroidSchedulersHandlerSchedulerTest *self);

FOUNDATION_EXPORT RxAndroidSchedulersHandlerSchedulerTest *new_RxAndroidSchedulersHandlerSchedulerTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RxAndroidSchedulersHandlerSchedulerTest *create_RxAndroidSchedulersHandlerSchedulerTest_init();

J2OBJC_TYPE_LITERAL_HEADER(RxAndroidSchedulersHandlerSchedulerTest)

#endif

#pragma pop_macro("INCLUDE_ALL_RxAndroidSchedulersHandlerSchedulerTest")
